minimum_pre_commit_version: 3.3.3

repos:
  - repo: local
    hooks:
      - id: ruff-lint
        name: ruff-lint
        entry: ruff --fix --config ./pyproject.toml
        language: system
        types: [python]
      
      - id: black-format
        name: ruff-lint
        entry: black --config ./pyproject.toml
        language: system
        types: [python]

      - id: mypy
        name: mypy
        entry: mypy --config-file ./pyproject.toml --enable-incomplete-feature=Unpack --install-types --non-interactive
        language: system
        types: [python]

      - id: ruff-check
        name: ruff-check
        entry: ruff check --config ./pyproject.toml
        language: system
        types: [python]

      - id: black-check
        name: black-check
        entry: black --check --config ./pyproject.toml
        language: system
        types: [python]