version: '3.9'

services:

  api:
    build: ./api
    restart: unless-stopped
    container_name: api
    env_file:
      - ./api/.env
    ports:
      - 9771:9771
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:9771"]
      timeout: 30s
      retries: 10
    volumes: 
      - ./api:/api
      - ./src:/api/src
      - ./models/codebert-bimodal/checkpoint-best-aver:/api/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]